### ISSUE TITLE
Server jar not compilable

### ISSUE THREAD

**Issue by svgas100** [hhu-bsinfo/dxterm#1]
I just downloaded the project and tried to compile it, but i wasnt able to, with following error message:
> Task :server:compileJava
~/dxterm-development/server/src/main/java/de/hhu/bsinfo/dxterm/server/TerminalServerApplication.java:61: error: TerminalServerApplication is not abstract and does not override abstract method main(String[]) in AbstractApplication
public class TerminalServerApplication extends AbstractApplication implements TerminalSession.Listener,
       ^
~/dxterm-development/server/src/main/java/de/hhu/bsinfo/dxterm/server/TerminalServerApplication.java:88: error: method does not override or implement a method from a supertype
    @Override
    ^
~/dxterm-development/server/src/main/java/de/hhu/bsinfo/dxterm/server/TerminalServerApplication.java:93: error: method does not override or implement a method from a supertype
    @Override
    ^
3 errors

Task :server:compileJava FAILED<

**Comment by stnot** [comment]
A lot has changed already and we are currently preparing another release which should fix various issues (including your compile problem). You can already checkout the development branch of DXRAM as well as the dxapps repository: https://github.com/hhu-bsinfo/dxapps
The application interface was refactored and we fixed all applications we are currently using for development and testing.
